name: Deploy AAD Scripts to Production

on: push

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: "Check Out"

      - uses: matt-ball/newman-action@master
        name: "Run group and CA objects"
        with:
          apiKey: ${{ secrets.NEWMAN_API_KEY }}
          collection: AAD Automation Groups.postman_collection.json
          environment: ${{ secrets.AUTOMATION_DAVE_AAD_ENVIRONMENT_KEY }}

      - name: Replace environment tokens
        uses: cschleiden/replace-tokens@v1.2
        with:
          files: DaveMan AAD Tenant.postman_environment.json
        env:
          CLIENT_ID: ${{ secrets.DAVEMAN_AAD_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DAVEMAN_ENV_CLIENT_SECRET }}

      - uses: matt-ball/newman-action@master
        name: "Update custom auth extension"
        with:
          apiKey: ${{ secrets.NEWMAN_API_KEY }}
          collection: DaveMan AAD Custom Auth Extensions.postman_collection.json
          environment: DaveMan AAD Tenant.postman_environment.json
  
