name: Newman Run

on: push

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: AAD Automation Groups.postman_collection.json
          environment: DaveMan AAD Tenant.postman_environment.json
